/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/ready": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Ready */
        get: operations["ready_ready_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Login */
        post: operations["login_api_v1_auth_login_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/decisions/application": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Score a credit application and persist the decision */
        post: operations["decide_application_api_v1_decisions_application_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/decisions/{decision_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Decision */
        get: operations["get_decision_api_v1_decisions__decision_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/decisions/{decision_id}/adverse-action": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Reg B adverse action notice (declined applications only) */
        get: operations["get_adverse_action_api_v1_decisions__decision_id__adverse_action_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/decisions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Decisions */
        get: operations["list_decisions_api_v1_decisions_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/entities/{application_id}/graph": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 2-hop application<->entity neighbourhood for the case graph */
        get: operations["get_entity_graph_api_v1_entities__application_id__graph_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/stream": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Live decision feed (SSE) */
        get: operations["stream_decisions_api_v1_stream_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/stream/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Stream Status */
        get: operations["stream_status_api_v1_stream_status_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/stream/switch": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Switch replay source (admin) */
        post: operations["switch_source_api_v1_stream_switch_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/stream/start": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Start replay (admin) */
        post: operations["start_stream_api_v1_stream_start_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/stream/stop": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Stop replay (admin) */
        post: operations["stop_stream_api_v1_stream_stop_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/metrics": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Metrics */
        get: operations["get_metrics_api_v1_metrics_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/metrics/drift": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Drift */
        get: operations["get_drift_api_v1_metrics_drift_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/metrics/drift/reset": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Reset thresholds (admin) */
        post: operations["reset_drift_api_v1_metrics_drift_reset_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/cases/{decision_id}/similar": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Nearest past cases by narrative embedding
         * @description Nearest case narratives by cosine similarity over the HNSW index.
         *
         *     Similarity answers "does this look like something I have seen before"; the entity graph
         *     answers "is this connected to something I have seen before". They are different questions and
         *     the console shows both.
         */
        get: operations["get_similar_cases_api_v1_cases__decision_id__similar_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/copilot/ask": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Ask the read-only analyst copilot about a decision
         * @description Explain a decision that has already been made.
         *
         *     Read-only by construction: the copilot reaches the database only through the tool registry in
         *     app/llm/tools.py, whose sessions run in a Postgres READ ONLY transaction that is always rolled
         *     back. There is no code path from here to a score or a decision (CLAUDE.md invariant 1).
         */
        post: operations["copilot_ask_api_v1_copilot_ask_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * AdverseActionNotice
         * @description Reg B (12 CFR 1002.9)-shaped notice. Applicant-facing: plain-language reasons only, no raw features/scores.
         */
        AdverseActionNotice: {
            /**
             * Decision Id
             * Format: uuid
             */
            decision_id: string;
            /**
             * Application Id
             * Format: uuid
             */
            application_id: string;
            action_taken: components["schemas"]["DecisionOutcome"];
            /**
             * Notice Date
             * Format: date-time
             */
            notice_date: string;
            /** Principal Reasons */
            principal_reasons: components["schemas"]["PrincipalReason"][];
            /** Ecoa Notice */
            ecoa_notice: string;
            /** Right To Request Reasons */
            right_to_request_reasons: string;
        };
        /**
         * ApplicationEvent
         * @description A raw credit application: every BAF column plus synthetic identifiers used for the entity graph.
         *
         *     Protected attributes (customer_age, employment_status, income) are accepted for fairness evaluation
         *     but are never model features (enforced in ml/featurize.py).
         */
        ApplicationEvent: {
            /** Income */
            income: number;
            /** Name Email Similarity */
            name_email_similarity: number;
            /** Prev Address Months Count */
            prev_address_months_count: number;
            /** Current Address Months Count */
            current_address_months_count: number;
            /** Customer Age */
            customer_age: number;
            /** Days Since Request */
            days_since_request: number;
            /** Intended Balcon Amount */
            intended_balcon_amount: number;
            /**
             * Payment Type
             * @enum {string}
             */
            payment_type: "AA" | "AB" | "AC" | "AD" | "AE";
            /** Zip Count 4W */
            zip_count_4w: number;
            /** Velocity 6H */
            velocity_6h: number;
            /** Velocity 24H */
            velocity_24h: number;
            /** Velocity 4W */
            velocity_4w: number;
            /** Bank Branch Count 8W */
            bank_branch_count_8w: number;
            /** Date Of Birth Distinct Emails 4W */
            date_of_birth_distinct_emails_4w: number;
            /**
             * Employment Status
             * @enum {string}
             */
            employment_status: "CA" | "CB" | "CC" | "CD" | "CE" | "CF" | "CG";
            /** Credit Risk Score */
            credit_risk_score: number;
            /**
             * Email Is Free
             * @enum {integer}
             */
            email_is_free: 0 | 1;
            /**
             * Housing Status
             * @enum {string}
             */
            housing_status: "BA" | "BB" | "BC" | "BD" | "BE" | "BF" | "BG";
            /**
             * Phone Home Valid
             * @enum {integer}
             */
            phone_home_valid: 0 | 1;
            /**
             * Phone Mobile Valid
             * @enum {integer}
             */
            phone_mobile_valid: 0 | 1;
            /** Bank Months Count */
            bank_months_count: number;
            /**
             * Has Other Cards
             * @enum {integer}
             */
            has_other_cards: 0 | 1;
            /** Proposed Credit Limit */
            proposed_credit_limit: number;
            /**
             * Foreign Request
             * @enum {integer}
             */
            foreign_request: 0 | 1;
            /**
             * Source
             * @enum {string}
             */
            source: "INTERNET" | "TELEAPP";
            /** Session Length In Minutes */
            session_length_in_minutes: number;
            /**
             * Device Os
             * @enum {string}
             */
            device_os: "windows" | "macintosh" | "linux" | "x11" | "other";
            /**
             * Keep Alive Session
             * @enum {integer}
             */
            keep_alive_session: 0 | 1;
            /** Device Distinct Emails 8W */
            device_distinct_emails_8w: number;
            /** Device Fraud Count */
            device_fraud_count: number;
            /** Month */
            month?: number | null;
            /** Device Id */
            device_id: string;
            /** Email */
            email: string;
            /** Phone */
            phone: string;
            /** Ip */
            ip: string;
            /** Address */
            address: string;
            /** Applicant Name */
            applicant_name: string;
            /** External Ref */
            external_ref?: string | null;
            /**
             * History
             * @default false
             */
            history: boolean;
            /** Fraud Bool */
            fraud_bool?: (0 | 1) | null;
        };
        /**
         * Band
         * @enum {string}
         */
        Band: "APPROVE" | "STEP_UP" | "REVIEW" | "DECLINE";
        /** CopilotAskRequest */
        CopilotAskRequest: {
            /**
             * Decision Id
             * Format: uuid
             */
            decision_id: string;
            /** Question */
            question: string;
        };
        /** CopilotAskResponse */
        CopilotAskResponse: {
            /** Answer */
            answer: string;
            /**
             * Cited Reasons
             * @description Feature keys of reason codes on this decision cited in the answer
             */
            cited_reasons: string[];
            /**
             * Blocked
             * @description True if guardrails refused the question
             */
            blocked: boolean;
            /**
             * Fallback Used
             * @description True if the LLM failed and a templated answer was returned
             */
            fallback_used: boolean;
        };
        /** DecisionList */
        DecisionList: {
            /** Items */
            items: components["schemas"]["DecisionResponse"][];
            /** Total */
            total: number;
            /** Limit */
            limit: number;
            /** Offset */
            offset: number;
        };
        /**
         * DecisionOutcome
         * @description What happens to the application. Band = risk tier; decision = resulting application status.
         * @enum {string}
         */
        DecisionOutcome: "approved" | "pending_verification" | "pending_review" | "declined";
        /** DecisionResponse */
        DecisionResponse: {
            /**
             * Decision Id
             * Format: uuid
             */
            decision_id: string;
            /**
             * Application Id
             * Format: uuid
             */
            application_id: string;
            /** External Ref */
            external_ref?: string | null;
            /** Score */
            score: number;
            band: components["schemas"]["Band"];
            decision: components["schemas"]["DecisionOutcome"];
            /** Reason Codes */
            reason_codes: components["schemas"]["ReasonCode"][];
            graph_signals: components["schemas"]["GraphSignals"];
            /** Graph Uplift */
            graph_uplift: number;
            /** Model Version */
            model_version: string;
            /** Latency Ms */
            latency_ms: number;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
        };
        /** DriftEventOut */
        DriftEventOut: {
            /** Id */
            id: number;
            /**
             * Ts
             * Format: date-time
             */
            ts: string;
            /** Detector */
            detector: string;
            /** Stream */
            stream: string;
            old_thresholds: components["schemas"]["Thresholds"];
            new_thresholds: components["schemas"]["Thresholds"];
            /** Details */
            details: {
                [key: string]: unknown;
            };
        };
        /** DriftStatus */
        DriftStatus: {
            /**
             * State
             * @enum {string}
             */
            state: "stable" | "drift_detected";
            thresholds: components["schemas"]["Thresholds"];
            base_thresholds: components["schemas"]["Thresholds"];
            /** Events */
            events: components["schemas"]["DriftEventOut"][];
        };
        /**
         * EntityGraphResponse
         * @description Bipartite application<->entity neighbourhood (2 hops, capped at GRAPH_MAX_NODES).
         */
        EntityGraphResponse: {
            /** Application Id */
            application_id: string;
            /** Nodes */
            nodes: components["schemas"]["GraphNode"][];
            /** Edges */
            edges: components["schemas"]["GraphEdge"][];
            /** Truncated */
            truncated: boolean;
        };
        /** ErrorResponse */
        ErrorResponse: {
            /** Detail */
            detail: string;
            /** Request Id */
            request_id?: string | null;
        };
        /** GraphEdge */
        GraphEdge: {
            /** Source */
            source: string;
            /** Target */
            target: string;
        };
        /** GraphNode */
        GraphNode: {
            /** Id */
            id: string;
            /**
             * Type
             * @enum {string}
             */
            type: "application" | "device" | "email" | "phone" | "ip" | "address";
            /** Label */
            label: string;
            /** Fraud */
            fraud: boolean;
        };
        /** GraphSignals */
        GraphSignals: {
            /**
             * Component Size
             * @default 0
             */
            component_size: number;
            /**
             * Distinct Names Per Device
             * @default 0
             */
            distinct_names_per_device: number;
            /**
             * Known Fraud 2Hop
             * @default 0
             */
            known_fraud_2hop: number;
            /**
             * Component Velocity 24H
             * @default 0
             */
            component_velocity_24h: number;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** HealthResponse */
        HealthResponse: {
            /**
             * Status
             * @constant
             */
            status: "ok";
        };
        /** LoginRequest */
        LoginRequest: {
            /** Username */
            username: string;
            /**
             * Password
             * Format: password
             */
            password: string;
        };
        /**
         * MetricsResponse
         * @description Rolling-window service metrics. Latency percentiles in milliseconds.
         */
        MetricsResponse: {
            /** P50 */
            p50: number;
            /** P95 */
            p95: number;
            /** P99 */
            p99: number;
            /** Decisions Per Sec */
            decisions_per_sec: number;
            /**
             * Band Mix
             * @description Fraction of decisions per band in the window (sums to 1)
             */
            band_mix: {
                [key: string]: number;
            };
            /**
             * Window
             * @description Number of decisions in the rolling window
             */
            window: number;
            /** Total Decisions */
            total_decisions: number;
        };
        /** PrincipalReason */
        PrincipalReason: {
            /** Rank */
            rank: number;
            /** Reason */
            reason: string;
            /** Ecoa Category */
            ecoa_category: string;
        };
        /** ReadyResponse */
        ReadyResponse: {
            /**
             * Status
             * @enum {string}
             */
            status: "ready" | "unavailable";
            /**
             * Database
             * @enum {string}
             */
            database: "ok" | "error";
        };
        /** ReasonCode */
        ReasonCode: {
            /** Feature */
            feature: string;
            /** Reason */
            reason: string;
            /** Ecoa Category */
            ecoa_category: string;
            /**
             * Contribution
             * @description SHAP contribution toward fraud (log-odds, > 0)
             */
            contribution: number;
        };
        /** SimilarCase */
        SimilarCase: {
            /**
             * Decision Id
             * Format: uuid
             */
            decision_id: string;
            /**
             * Application Id
             * Format: uuid
             */
            application_id: string;
            /**
             * Similarity
             * @description Cosine similarity of case narratives
             */
            similarity: number;
            /** Score */
            score: number;
            band: components["schemas"]["Band"];
            /**
             * Top Reasons
             * @description Reason texts of the similar case, highest contribution first
             */
            top_reasons: string[];
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
        };
        /** SimilarCasesResponse */
        SimilarCasesResponse: {
            /**
             * Decision Id
             * Format: uuid
             */
            decision_id: string;
            /** K */
            k: number;
            /** Items */
            items: components["schemas"]["SimilarCase"][];
        };
        /** StreamStatus */
        StreamStatus: {
            /** Running */
            running: boolean;
            /**
             * Source
             * @enum {string}
             */
            source: "base" | "shift";
            /** Events Emitted */
            events_emitted: number;
            /** Rate Per Sec */
            rate_per_sec: number;
            /** Subscribers */
            subscribers: number;
        };
        /**
         * Thresholds
         * @description Score cut-offs: APPROVE < step_up <= STEP_UP < review <= REVIEW < decline <= DECLINE.
         */
        Thresholds: {
            /** Step Up */
            step_up: number;
            /** Review */
            review: number;
            /** Decline */
            decline: number;
        };
        /** TokenResponse */
        TokenResponse: {
            /** Access Token */
            access_token: string;
            /**
             * Token Type
             * @default bearer
             * @constant
             */
            token_type: "bearer";
            /**
             * Role
             * @enum {string}
             */
            role: "analyst" | "admin";
            /** Expires In */
            expires_in: number;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    health_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthResponse"];
                };
            };
        };
    };
    ready_ready_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReadyResponse"];
                };
            };
            /** @description Database unreachable */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReadyResponse"];
                };
            };
        };
    };
    login_api_v1_auth_login_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TokenResponse"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    decide_application_api_v1_decisions_application_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ApplicationEvent"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DecisionResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_decision_api_v1_decisions__decision_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                decision_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DecisionResponse"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_adverse_action_api_v1_decisions__decision_id__adverse_action_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                decision_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AdverseActionNotice"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Not a declined application */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_decisions_api_v1_decisions_get: {
        parameters: {
            query?: {
                band?: components["schemas"]["Band"] | null;
                limit?: number;
                offset?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DecisionList"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_entity_graph_api_v1_entities__application_id__graph_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                application_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EntityGraphResponse"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    stream_decisions_api_v1_stream_get: {
        parameters: {
            query?: {
                /** @description JWT; EventSource cannot send an Authorization header */
                token?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Server-Sent Events. `event: decision` carries a DecisionResponse JSON in `data`; `event: drift` carries a DriftEventOut JSON; `: ping` comments every 15 s keep the connection open. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/event-stream": components["schemas"]["DecisionResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    stream_status_api_v1_stream_status_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StreamStatus"];
                };
            };
        };
    };
    switch_source_api_v1_stream_switch_post: {
        parameters: {
            query: {
                /** @description base = test months of Base; shift = variant file */
                source: "base" | "shift";
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StreamStatus"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    start_stream_api_v1_stream_start_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StreamStatus"];
                };
            };
        };
    };
    stop_stream_api_v1_stream_stop_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StreamStatus"];
                };
            };
        };
    };
    get_metrics_api_v1_metrics_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MetricsResponse"];
                };
            };
        };
    };
    get_drift_api_v1_metrics_drift_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DriftStatus"];
                };
            };
        };
    };
    reset_drift_api_v1_metrics_drift_reset_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DriftStatus"];
                };
            };
        };
    };
    get_similar_cases_api_v1_cases__decision_id__similar_get: {
        parameters: {
            query?: {
                k?: number;
            };
            header?: never;
            path: {
                decision_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SimilarCasesResponse"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    copilot_ask_api_v1_copilot_ask_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CopilotAskRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CopilotAskResponse"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
