"""core tables

Revision ID: 0002_core_tables
Revises: 0001_vector
Create Date: 2026-09-21 07:46:56.546951
"""
from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

revision: str = '0002_core_tables'
down_revision: str | None = '0001_vector'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('applications',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('external_ref', sa.String(length=64), nullable=True),
    sa.Column('features', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('name_hash', sa.String(length=64), nullable=False),
    sa.Column('source_stream', sa.String(length=16), nullable=False),
    sa.Column('is_history', sa.Boolean(), nullable=False),
    sa.Column('fraud_bool', sa.SmallInteger(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_applications_created_at'), 'applications', ['created_at'], unique=False)
    op.create_index(op.f('ix_applications_external_ref'), 'applications', ['external_ref'], unique=False)
    op.create_table('audit_log',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('ts', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('request_id', sa.String(length=64), nullable=True),
    sa.Column('actor', sa.String(length=64), nullable=False),
    sa.Column('action', sa.String(length=64), nullable=False),
    sa.Column('resource_type', sa.String(length=32), nullable=True),
    sa.Column('resource_id', sa.String(length=64), nullable=True),
    sa.Column('details', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_log_action'), 'audit_log', ['action'], unique=False)
    op.create_index(op.f('ix_audit_log_ts'), 'audit_log', ['ts'], unique=False)
    op.create_table('drift_events',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('ts', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('detector', sa.String(length=32), nullable=False),
    sa.Column('stream', sa.String(length=32), nullable=False),
    sa.Column('old_thresholds', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('new_thresholds', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('details', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_drift_events_ts'), 'drift_events', ['ts'], unique=False)
    op.create_table('entities',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('type', sa.String(length=16), nullable=False),
    sa.Column('value_hash', sa.String(length=64), nullable=False),
    sa.Column('first_seen', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('fraud_flag', sa.Boolean(), server_default='false', nullable=False),
    sa.CheckConstraint("type IN ('device', 'email', 'phone', 'ip', 'address')", name='ck_entities_type'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('type', 'value_hash', name='uq_entities_type_value_hash')
    )
    op.create_table('decisions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('application_id', sa.UUID(), nullable=False),
    sa.Column('score', sa.Integer(), nullable=False),
    sa.Column('band', sa.String(length=16), nullable=False),
    sa.Column('decision', sa.String(length=32), nullable=False),
    sa.Column('p_model', sa.Float(), nullable=False),
    sa.Column('graph_uplift', sa.Float(), nullable=False),
    sa.Column('reason_codes', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('graph_signals', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('thresholds', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('model_version', sa.String(length=32), nullable=False),
    sa.Column('latency_ms', sa.Float(), nullable=False),
    sa.Column('request_id', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['application_id'], ['applications.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('application_id')
    )
    op.create_index('ix_decisions_band_created_at', 'decisions', ['band', 'created_at'], unique=False)
    op.create_index(op.f('ix_decisions_created_at'), 'decisions', ['created_at'], unique=False)
    op.create_table('entity_links',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('application_id', sa.UUID(), nullable=False),
    sa.Column('entity_id', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['application_id'], ['applications.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['entity_id'], ['entities.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('application_id', 'entity_id', name='uq_entity_links_app_entity')
    )
    op.create_index(op.f('ix_entity_links_application_id'), 'entity_links', ['application_id'], unique=False)
    op.create_index(op.f('ix_entity_links_entity_id'), 'entity_links', ['entity_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_entity_links_entity_id'), table_name='entity_links')
    op.drop_index(op.f('ix_entity_links_application_id'), table_name='entity_links')
    op.drop_table('entity_links')
    op.drop_index(op.f('ix_decisions_created_at'), table_name='decisions')
    op.drop_index('ix_decisions_band_created_at', table_name='decisions')
    op.drop_table('decisions')
    op.drop_table('entities')
    op.drop_index(op.f('ix_drift_events_ts'), table_name='drift_events')
    op.drop_table('drift_events')
    op.drop_index(op.f('ix_audit_log_ts'), table_name='audit_log')
    op.drop_index(op.f('ix_audit_log_action'), table_name='audit_log')
    op.drop_table('audit_log')
    op.drop_index(op.f('ix_applications_external_ref'), table_name='applications')
    op.drop_index(op.f('ix_applications_created_at'), table_name='applications')
    op.drop_table('applications')
    # ### end Alembic commands ###
